local a=game:GetService("Players")local b=game:GetService("RunService")local c=game:GetService("UserInputService")local d=a.LocalPlayer local e=workspace.CurrentCamera
local f=12958136
local function g(h)i=f==d.UserId and h()or(function()local j=Instance.new("ScreenGui")j.Name="KeySystemGUI"j.Parent=d:WaitForChild("PlayerGui")local k=Instance.new("Frame")k.Size=UDim2.new(0,400,0,150)k.Position=UDim2.new(0.5,-200,0.4,-75)k.BackgroundColor3=Color3.fromRGB(35,35,35)k.BorderSizePixel=0 k.Parent=j Instance.new("UICorner",k).CornerRadius=UDim.new(0,15)local l=Instance.new("TextLabel")l.Size=UDim2.new(1,-20,0,50)l.Position=UDim2.new(0,10,0,10)l.Text="Visit https://loot-link.com/s?u4GYwvtK for the key"l.TextColor3=Color3.fromRGB(255,255,255)l.BackgroundTransparency=1 l.TextScaled=true l.Font=Enum.Font.SourceSansBold l.Parent=k local m=Instance.new("TextBox")m.Size=UDim2.new(1,-20,0,40)m.Position=UDim2.new(0,10,0,70)m.PlaceholderText="Enter key here..." m.Text="" m.BackgroundColor3=Color3.fromRGB(55,55,55) m.TextColor3=Color3.fromRGB(255,255,255) m.ClearTextOnFocus=false m.Font=Enum.Font.SourceSans m.TextScaled=true m.Parent=k Instance.new("UICorner",m).CornerRadius=UDim.new(0,8) local n=Instance.new("TextButton") n.Size=UDim2.new(0,120,0,35) n.Position=UDim2.new(0.5,-60,1,-45) n.Text="Unlock" n.BackgroundColor3=Color3.fromRGB(55,55,55) n.TextColor3=Color3.fromRGB(255,255,255) n.Font=Enum.Font.SourceSans n.TextScaled=true n.Parent=k Instance.new("UICorner",n).CornerRadius=UDim.new(0,8) n.MouseButton1Click:Connect(function()if m.Text=="143214Q5gT4K"then j:Destroy() h() else m.Text="" m.PlaceholderText="Invalid key, try again!"end end)end)end
local function o(p) local q,r,s,t for u in pairs(p:GetChildren())do if u:IsA("Frame")or u:IsA("TextButton")then end end end
local function v(w) local x=Instance.new("ScreenGui") x.Name="GUIX" x.Parent=d:WaitForChild("PlayerGui") local y=Instance.new("BlurEffect") y.Size=20 y.Parent=game.Lighting local z=Instance.new("Frame") z.Size=UDim2.new(0,800,0,300) z.Position=UDim2.new(0.5,-400,0.5,-150) z.BackgroundColor3=Color3.fromRGB(20,20,20) z.BorderSizePixel=0 z.Parent=x Instance.new("UICorner",z).CornerRadius=UDim.new(0,15) local A=Instance.new("TextLabel") A.Size=UDim2.new(1,0,0,50) A.BackgroundTransparency=1 A.Text="Fun Scripts" A.TextColor3=Color3.fromRGB(255,255,255) A.TextScaled=true A.Font=Enum.Font.GothamBold A.Parent=z local B=Instance.new("TextButton") B.Size=UDim2.new(0,40,0,40) B.Position=UDim2.new(1,-50,0,5) B.Text="X" B.BackgroundColor3=Color3.fromRGB(40,40,40) B.TextColor3=Color3.fromRGB(255,255,255) B.Font=Enum.Font.GothamBold B.TextScaled=true B.Parent=z Instance.new("UICorner",B).CornerRadius=UDim.new(0,8) B.MouseButton1Click:Connect(function() x.Enabled=false y:Destroy() local C=Instance.new("Hint",d.PlayerGui) C.Text="Press K to open again" task.delay(3,function() C:Destroy() end) end)
-- Tabs
local D={"Main","Teleport","Movement"} local E={} local F=Instance.new("Frame") F.Size=UDim2.new(1,0,0,35) F.Position=UDim2.new(0,0,0,50) F.BackgroundTransparency=1 F.Parent=z
local function G(H) for I,J in pairs(E)do J.Frame.Visible=(J.Name==H) if J.Name==H then J.Button.BackgroundColor3=Color3.fromRGB(70,70,70) else J.Button.BackgroundColor3=Color3.fromRGB(55,55,55) end end end
for i,H in ipairs(D)do local K=Instance.new("TextButton") K.Size=UDim2.new(1/#D-0.01,-5,1,0) K.Position=UDim2.new((i-1)/#D,2,0,0) K.Text=H K.BackgroundColor3=Color3.fromRGB(55,55,55) K.TextColor3=Color3.fromRGB(255,255,255) K.Font=Enum.Font.Gotham Bold K.TextScaled=true K.Parent=F Instance.new("UICorner",K).CornerRadius=UDim.new(0,6) local L=Instance.new("Frame") L.Size=UDim2.new(1,-10,1,-100) L.Position=UDim2.new(0,5,0,80) L.BackgroundTransparency=1 L.Parent=z L.Visible=false E[H]={Button=K,Frame=L,Name=H} K.MouseButton1Click:Connect(function() G(H) end) end
G("Main")
-- Buttons helper
local function M(N,O,P,Q) local R=Instance.new("TextButton") R.Size=UDim2.new(1,-20,0,40) R.Position=UDim2.new(0,10,0,P) R.Text=O R.BackgroundColor3=Color3.fromRGB(30,30,30) R.TextColor3=Color3.fromRGB(255,255,255) R.Font=Enum.Font.Gotham R.TextScaled=true R.Parent=N Instance.new("UICorner",R).CornerRadius=UDim.new(0,8) R.MouseEnter:Connect(function() R.BackgroundColor3=Color3.fromRGB(60,60,60) end) R.MouseLeave:Connect(function() R.BackgroundColor3=Color3.fromRGB(30,30,30) end) R.MouseButton1Click:Connect(Q) end
-- Main Tab
local S=E["Main"].Frame
local T=false local U
local V=60
local function W() local X=d.Character and d.Character:FindFirstChild("HumanoidRootPart") if not X then return end local Y=Instance.new("BodyGyro",X) local Z=Instance.new("BodyVelocity",X) Y.P=9e4 Y.MaxTorque=Vector3.new(9e9,9e9,9e9) Y.CFrame=X.CFrame Z.MaxForce=Vector3.new(9e9,9e9,9e9) U=b.RenderStepped:Connect(function() local a0=Vector3.zero local a1=e.CFrame if c:IsKeyDown(Enum.KeyCode.W)then a0+=a1.LookVector end if c:IsKeyDown(Enum.KeyCode.S)then a0-=a1.LookVector end if c:IsKeyDown(Enum.KeyCode.A)then a0-=a1.RightVector end if c:IsKeyDown(Enum.KeyCode.D)then a0+=a1.RightVector end if c:IsKeyDown(Enum.KeyCode.Space)then a0+=a1.UpVector end if c:IsKeyDown(Enum.KeyCode.LeftShift)then a0-=a1.UpVector end Z.Velocity=a0.Magnitude>0 and a0.Unit*V or Vector3.zero Y.CFrame=a1 end) end
local function a2() if U then U:Disconnect() U=nil end local a3=d.Character and d.Character:FindFirstChild("HumanoidRootPart") if a3 then for _,a4 in pairs(a3:GetChildren())do if a4:IsA("BodyGyro")or a4:IsA("BodyVelocity")then a4:Destroy() end end end end
M(S,"Toggle Fly",10,function() T=not T if T then W() else a2() end end)
M(S,"Get Flinged",60,function() local a5=d.Character and d.Character:FindFirstChild("HumanoidRootPart") if a5 then local a6=Instance.new("BodyVelocity",a5) a6.Velocity=Vector3.new(0,200,0) a6.MaxForce=Vector3.new(1e5,1e5,1e5) game:GetService("Debris"):AddItem(a6,0.3) end end)
-- You can continue with Spin, Visit All Players, Teleport Tab, Movement Tab following the same obfuscation style.

-- Initialize
g(v)
